#install.packages('shiny', repos='https://cran.rstudio.com/')
#install.packages("readr",repos="https://cran.wu.ac.at")
#lib='/home/bitnami/Project/CityApp/R/'
#library(devtools)
# load package w/o installing
#load_all('/home/bitnami/Project/CityApp/R')
#install.packages("openxlsx", dependencies=TRUE,lib='/home/bitnami/Project/CityApp/R',repos="https://cran.wu.ac.at")
#install.packages("openxlsx",lib='/home/bitnami/Project/CityApp/R', dependencies=TRUE,,repos="https://cran.wu.ac.at")
#install.packages("mice",lib='/home/bitnami/Project/CityApp/R',repos="https://cran.wu.ac.at")
#install.packages("libcurl4-openssl-dev",repos="https://cran.wu.ac.at")
#install.packages("rio",,repos="https://cran.wu.ac.at")
#install.packages("car",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("VIM",lib='/home/bitnami/Project/CityApp/R',repos="https://cran.wu.ac.at")
#install.packages("ggmap",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("ggplot2",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("tidyverse",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("rpart",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("DMwR",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("caret",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")
#install.packages("rjson",lib='/home/bitnami/Project/CityApp/R/',repos="https://cran.wu.ac.at")

#Install all packages required for R code
install.packages("mice",repos="https://cran.wu.ac.at")
install.packages("VIM",repos="https://cran.wu.ac.at")
#install.packages("png",repos="https://cran.wu.ac.at")
#library(png)
#install.packages("RgoogleMaps",repos="https://cran.wu.ac.at")
install.packages("ggmap",repos="https://cran.wu.ac.at",dependencies = TRUE)
install.packages("ggplot2",repos="https://cran.wu.ac.at",,dependencies = TRUE)
#install.packages("xml2",repos="http://www.rforge.net/png/")
#install.packages("rvest",repos="https://cran.wu.ac.at")
#install.packages(c('tidyverse'), repos='http://lib.stat.cmu.edu/R/CRAN/')
#install.packages("tidyverse",repos='http://lib.stat.cmu.edu/R/CRAN/',dependencies = TRUE)
install.packages("rpart",repos="https://cran.wu.ac.at")
install.packages("DMwR",repos="https://cran.wu.ac.at")
install.packages("caret",repos="https://cran.wu.ac.at")
install.packages("rjson",repos="https://cran.wu.ac.at")
install.packages("gmodels",repos="https://cran.wu.ac.at")
